In [20]:
import numpy as np

In [8]:
shape = [102,46, 22]

In [9]:
r = np.random.rand(*shape)
X = np.zeros(shape)

In [18]:
X[r<0.75] = np.random.uniform(-1111, -1110, X[r<0.75].shape)

In [19]:
X

array([[[    0.        , -1110.8673083 , -1110.41761841, ...,
         -1110.49060394, -1110.67585298,     0.        ],
        [-1110.28248201,     0.        , -1110.39698438, ...,
             0.        ,     0.        , -1110.70699402],
        [-1110.03610764, -1110.03709629, -1110.63304162, ...,
         -1110.23479105, -1110.76495533,     0.        ],
        ..., 
        [    0.        , -1110.38327269, -1110.92078016, ...,
         -1110.2396013 , -1110.26390374, -1110.43661305],
        [    0.        ,     0.        , -1110.01959273, ...,
         -1110.8841552 , -1110.74471225, -1110.09064218],
        [-1110.7732823 , -1110.22976333, -1110.02704919, ...,
             0.        , -1110.42897436, -1110.51638911]],

       [[-1110.33363909, -1110.35256235, -1110.39674583, ...,
         -1110.9097853 , -1110.07767672, -1110.33850339],
        [-1110.16838872, -1110.642052  ,     0.        , ...,
             0.        , -1110.79913524, -1110.80153103],
        [    0.        ,

In [13]:
X[r<0.75].shape

(77266,)

In [15]:
np.where(r < 0.75)

(array([  0,   0,   0, ..., 101, 101, 101]),
 array([ 0,  0,  0, ..., 45, 45, 45]),
 array([ 1,  2,  3, ..., 17, 18, 20]))

In [21]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.float32(np.append(np.identity(5), np.zeros([5, 1]), 1))

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.]], dtype=float32)

In [23]:
a = np.random.rand(10,2,3)
b = np.random.rand(3,1)

In [26]:
c = a * b[:,:,np.newaxis].T

In [27]:
c.shape

(10, 2, 3)

In [30]:
a[..., 0] * b[0] == c[...,0]

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)

array([[ 0.07250769,  0.00071089],
       [ 0.03906824,  0.09093782],
       [ 0.09840578,  0.10850073],
       [ 0.01253854,  0.06005405],
       [ 0.00635429,  0.02405075],
       [ 0.04357959,  0.0915284 ],
       [ 0.02159493,  0.06410345],
       [ 0.00248041,  0.02662878],
       [ 0.08751435,  0.04037163],
       [ 0.05212227,  0.09910217]])

In [31]:
b = np.random.rand(100,3)

In [35]:
w = np.random.rand(3,6*7)

In [38]:
b[:,0] * w[0:1].T

array([[ 0.01053198,  0.4531398 ,  0.15559207, ...,  0.14101534,
         0.00304404,  0.41640273],
       [ 0.01843064,  0.79298066,  0.27228132, ...,  0.24677248,
         0.00532697,  0.72869191],
       [ 0.00885642,  0.38104849,  0.13083848, ...,  0.1185808 ,
         0.00255975,  0.35015602],
       ..., 
       [ 0.01452648,  0.62500355,  0.21460397, ...,  0.19449866,
         0.00419856,  0.57433309],
       [ 0.00788648,  0.33931685,  0.11650932, ...,  0.10559408,
         0.00227941,  0.31180766],
       [ 0.0086685 ,  0.37296346,  0.12806237, ...,  0.11606477,
         0.00250544,  0.34272646]])

In [39]:
_.shape

(42, 100)

In [40]:
b[:,0].shape

(100,)

In [41]:
w[0:1].T.shape

(42, 1)

In [42]:
import tensorflow as tf

In [43]:
x = tf.Variable(np.random.rand(100,2))

In [44]:
y = x[:, tf.newaxis, tf.newaxis, :]

In [45]:
x

<tf.Variable 'Variable:0' shape=(100, 2) dtype=float64_ref>

In [47]:
y = tf.Variable(np.random.rand(100,1))

In [49]:
tf.pad(x, [[0,0],[0,1]], "CONSTANT")

<tf.Tensor 'Pad:0' shape=(100, 3) dtype=float64>

In [50]:
np.ones((5, 5)) - np.identity(5)

array([[ 0.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  1.,  1.,  1.],
       [ 1.,  1.,  0.,  1.,  1.],
       [ 1.,  1.,  1.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  0.]])

In [51]:
help(tf.matrix_diag)

Help on function matrix_diag in module tensorflow.python.ops.gen_array_ops:

matrix_diag(diagonal, name=None)
    Returns a batched diagonal tensor with a given batched diagonal values.
    
    Given a `diagonal`, this operation returns a tensor with the `diagonal` and
    everything else padded with zeros. The diagonal is computed as follows:
    
    Assume `diagonal` has `k` dimensions `[I, J, K, ..., N]`, then the output is a
    tensor of rank `k+1` with dimensions [I, J, K, ..., N, N]` where:
    
    `output[i, j, k, ..., m, n] = 1{m=n} * diagonal[i, j, k, ..., n]`.
    
    For example:
    
    ```
    # 'diagonal' is [[1, 2, 3, 4], [5, 6, 7, 8]]
    
    and diagonal.shape = (2, 4)
    
    tf.matrix_diag(diagonal) ==> [[[1, 0, 0, 0]
                                         [0, 2, 0, 0]
                                         [0, 0, 3, 0]
                                         [0, 0, 0, 4]],
                                        [[5, 0, 0, 0]
                           

In [54]:
m = tf.matrix_diag(np.float32(np.ones((num_agents, num_agents)) - np.identity(num_agents)))

In [53]:
num_agents = 5

In [55]:
m

<tf.Tensor 'MatrixDiag:0' shape=(5, 5, 5) dtype=float32>

In [56]:
sess = tf.InteractiveSession()

In [62]:
m = sess.run(m)

In [58]:
a = np.random.rand(3,5)

In [64]:
np.matmul(a, m[2])

array([[ 0.25483529,  0.41485706,  0.        ,  0.98024201,  0.81785613],
       [ 0.4133716 ,  0.52512081,  0.        ,  0.1778869 ,  0.47538863],
       [ 0.04949664,  0.22042945,  0.        ,  0.91068207,  0.14047805]])

In [60]:
a

array([[ 0.25483529,  0.41485706,  0.31445759,  0.98024201,  0.81785613],
       [ 0.4133716 ,  0.52512081,  0.78051709,  0.1778869 ,  0.47538863],
       [ 0.04949664,  0.22042945,  0.95728169,  0.91068207,  0.14047805]])

In [61]:
m[1]

<tf.Tensor 'strided_slice_2:0' shape=(5, 5) dtype=float32>